# This workflow is largely based on
# https://github.com/salsify/ember-css-modules/blob/master/.github/workflows/ci.yml

name: CI

on:
  pull_request:
  push:
    # filtering branches here prevents duplicate builds from pull_request and push
    branches:
      - main

env:
  CI: true

jobs:
  lint-js:
    name: lint:js
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - run: pnpm run -r --parallel --aggregate-output lint:js

  lint-hbs:
    name: lint:hbs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - run: pnpm run -r --parallel --aggregate-output lint:hbs

  lint-types:
    name: lint:types
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - run: pnpm run -r --parallel --aggregate-output lint:types

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Tests
        run: pnpm test
      # For the Try Scenarios
      - id: set-matrix
        run: |
          echo "matrix=$(pnpm -s dlx @embroider/try list)" >> $GITHUB_OUTPUT

  try-scenarios:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    needs: test
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.test.outputs.matrix)}}

    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
        with:
          install: false
      - name: Apply Scenario
        run: pnpm dlx @embroider/try apply ${{ matrix.name }}
      - name: Install Dependencies
        run: pnpm install --no-lockfile
      - name: Run Tests
        run: pnpm test
        env: ${{ matrix.env }}

  # test-try:
  #   name: Ember Try
  #   runs-on: ubuntu-24.04
  #   needs: [test-locked-deps]

  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       try-scenario:
  #         - ember-3.28
  #         - ember-4.4
  #         - ember-4.8
  #         - ember-4.12
  #         - ember-5.4
  #         - without-polaris-service
  #         - ember-release
  #         - ember-beta
  #         - ember-canary
  #         - embroider-safe
  #         - embroider-optimized
  #   steps:
  #     - name: Setup
  #       uses: wyvox/action@v1
  #     - name: Build package
  #       run: pnpm --filter ember-sweet-owner build
  #     - name: Try Scenario
  #       run: pnpm exec ember try:one ${{ matrix.try-scenario }} --skip-cleanup
  #       working-directory: test-app
